[build]
  publish = "frontend"
  command = ""

# No build command needed for static site
[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 